"""empty message

Revision ID: 3b9b1486830b
Revises: d7bd5c50e7f7
Create Date: 2017-06-21 17:00:25.831287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9b1486830b'
down_revision = 'd7bd5c50e7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('measurement', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('price', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'measurement')
    op.drop_column('products', 'image')
    op.drop_column('products', 'description')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
