"""empty message

Revision ID: 79756a39ca9c
Revises: 3b9b1486830b
Create Date: 2017-06-23 16:02:22.332073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79756a39ca9c'
down_revision = '3b9b1486830b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('firstName', sa.String(length=500), nullable=True),
    sa.Column('lastName', sa.String(length=500), nullable=True),
    sa.Column('profileThumbnailUrl', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
